### PR TITLE
Move prop-types to externals

### PR DESCRIPTION
**Pull request by intrueder**
Exclude `prop-types` from bundle moving the package to `externals`

### CODE REVIEW

**Comment by iqnivek** [comment]
Hey! Thanks for creating a PR, but could you explain what this helps accomplish? If this happens to be for dealing with #19 (the "Calling PropTypes validators" react warning), that should be solved now.

**Comment by intrueder** [comment]
Hi @iqnivek ,

Moving referenced package to externals will exclude it from the bundle (less size, less download time). The most react apps do already use `prop-types` package, so there is no need to include it in this component's webpack bundle. As a side effect, it solves #19 :)

Also see https://github.com/OscarBarrett/prop-types-externals-example

**Comment by iqnivek** [comment]
Got it. #19 is already fixed by updating prop-types, though. I think adding to externals is problematic because there's no guarantee that a react project has prop-types (if they're still using React.PropTypes, or if they're just not using proptypes at all). If prop-types were specified in peerDependencies, having it in externals would be fine, but the [prop-types documentation](https://www.npmjs.com/package/prop-types#how-to-depend-on-this-package) recommends to have the package in dependencies, not peerDependencies. So I don't think I can take this change in. If I'm actually wrong in my assessment, point me to the relevant details and I'd be happy to reopen. Thanks!

**Comment by intrueder** [comment]
Please, read the **Note** section in `How to Depend on This Package?` section:

> For UMD bundles of your comoponents, make sure you **don’t** include `PropTypes` in the build. Usually this is done by marking it as an external (the specifics depend on your bundler), just like you do with React.

**Comment by intrueder** [comment]
@iqnivek Did you get a chance to read the notes?

**Pull request closed without merging**
